### ISSUE TITLE
Inception

### ISSUE THREAD

**Issue by Ludocius** [improve-devs/Currency_conversion#1]
This meeting is required to all members in this project to split out each user story in accordance with the exercise posted.
1.We will discuss about the architecture and design about.
2.We will choose the technological stack to end up.

First members
@TheLuisBolivar 
@Ludocius

**Comment by Ludocius** [comment]
![image](https://user-images.githubusercontent.com/59232095/148864416-651d670a-c870-49f4-bf60-fe32957af3bc.png)

**Comment by TheLuisBolivar** [comment]
Acá dejo un poco de los modelos planteados para la solución: https://docs.google.com/spreadsheets/d/17CYbZ6lhh1Xvb3qJ_u0iZgWNC44o7-LVn8t0cev2Lm4/edit?usp=sharing

**Comment by TheLuisBolivar** [comment]
<img width="996" alt="Screen Shot 2022-01-11 at 19 39 28" src="https://user-images.githubusercontent.com/12574917/149048619-64659278-2b87-4160-b60f-be377cfd8c6e.png">

**Comment by TheLuisBolivar** [comment]
<img width="776" alt="Screen Shot 2022-01-11 at 19 40 07" src="https://user-images.githubusercontent.com/12574917/149048665-300e59ba-6ae4-4ca9-b60b-26b00f7be4fd.png">

**Comment by TheLuisBolivar** [comment]
<img width="911" alt="Screen Shot 2022-01-11 at 19 40 29" src="https://user-images.githubusercontent.com/12574917/149048692-518a352e-4ffa-4556-a5df-ae7f6fa6589e.png">

**Comment by TheLuisBolivar** [comment]
Pensar en seguridad

**Comment by TheLuisBolivar** [comment]
Jmeter para pruebas de tolerancia
